import type { Rng } from '../core/rng/index.ts';
import { shuffleInPlace } from '../core/rng/index.ts';

/**
 * First names for NPCs (AGENTS.md §8.3): a varied mix of Brazilian and international names,
 * deliberately without surnames so that none refers to a real public figure.
 */
const NAMES = [
  'Ana',
  'Bruno',
  'Camila',
  'Diego',
  'Elisa',
  'Felipe',
  'Gabriela',
  'Heitor',
  'Isabela',
  'João',
  'Karina',
  'Lucas',
  'Mariana',
  'Nicolas',
  'Olívia',
  'Pedro',
  'Rafaela',
  'Sofia',
  'Thiago',
  'Vitória',
  'Yasmin',
  'Beatriz',
  'Caio',
  'Débora',
  'Enzo',
  'Fernanda',
  'Gustavo',
  'Helena',
  'Igor',
  'Júlia',
  'Leonardo',
  'Marcos',
  'Natália',
  'Rodrigo',
  'Sérgio',
  'Valéria',
  'Lara',
  'Renata',
  'Samuel',
  'Tânia',
  'Vicente',
  'Paula',
  'Otávio',
  'Aiko',
  'Liam',
  'Emma',
  'Mateo',
  'Chloé',
  'Luca',
  'Noah',
  'Ingrid',
  'Sven',
  'Priya',
  'Kenji',
  'Amara',
  'Nina',
  'Otto',
  'Ravi',
  'Freya',
  'Tomás',
  'Inês',
  'Hugo',
  'Zara',
  'Malik',
  'Anya',
  'Élise',
  'Henrique',
] as const;

/** `count` distinct random names. */
export function pickNames(count: number, rng: Rng): string[] {
  if (count > NAMES.length) throw new RangeError('Not enough names');
  return shuffleInPlace([...NAMES], rng).slice(0, count);
}
